name: galaktika_sklad
description: Складское приложение для судостроительной компании "ГАЛАКТИКА"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  intl: ^0.19.0
  mobile_scanner: ^5.2.3

  # Firebase добавлены для будущей интеграции (не активны по умолчанию)
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/background.png

  fonts:
    - family: TacticSans
      fonts:
        - asset: assets/fonts/TacticSansExtExd-Bld.otf
          weight: 700
        - asset: assets/fonts/TacticSansExd-Med.otf
          weight: 500
